steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG=$(date -u +%Y%m%d-%H%M%S)
        docker build -t ${_ARTIFACT_REGISTRY_URL}/api-backend:latest -t ${_ARTIFACT_REGISTRY_URL}/api-backend:$TAG .

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_ARTIFACT_REGISTRY_URL}/api-backend:latest'
  - '${_ARTIFACT_REGISTRY_URL}/api-backend:$(date -u +%Y%m%d-%H%M%S)'