steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY_URL}/pricing-update-job:latest'
      - '-t'
      - '${_ARTIFACT_REGISTRY_URL}/pricing-update-job:$SHORT_SHA'
      - '.'
    dir: 'pricing-update-job'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_ARTIFACT_REGISTRY_URL}/pricing-update-job:latest'
  - '${_ARTIFACT_REGISTRY_URL}/pricing-update-job:$SHORT_SHA'